using System.Text.RegularExpressions;
using Memento.Core.Bridge.Contracts;
using Memento.Documents.Model;
using Memento.Documents.Model.Blocks;
using Memento.Documents.Model.Modules;
using Memento.Documents.Templates;
using TranscriptLine = Memento.Documents.Model.Blocks.TranscriptLine;

namespace Memento.Generation.Documents;

/// <summary>
/// Places the modules that come from the project's data, with no AI involved (ARCHITECTURE.md §8): Full transcript (every
/// segment with its speaker and time, chapter headings in place), Participants (the details and the named speakers),
/// Chapters, Highlights, Notes, Title, Custom text, the agenda with the coverage the user marked, the meeting purpose
/// from the details, and the quote candidates (highlighted segments) the Quote module prefers.
/// </summary>
public static partial class DataModuleComposer
{
    public const string NotDiscussed = "Not discussed.";

    /// <summary>The blocks of a data or user module, or <c>null</c> when <paramref name="module"/> is generated by AI.</summary>
    public static IReadOnlyList<Block>? Compose(TemplateModule module, ModuleDefinition? definition, RecordingMaterial material)
    {
        ArgumentNullException.ThrowIfNull(module);
        ArgumentNullException.ThrowIfNull(material);
        return module.Type switch
        {
            ModuleIds.FullTranscript => [FullTranscript(material)],
            ModuleIds.Participants => Participants(material) is { Count: > 0 } names ? [new ChipsBlock { Items = names }] : [Note("No participants were listed and no speaker was named.")],
            ModuleIds.Chapter => Chapters(material),
            ModuleIds.Highlight => Highlights(material),
            ModuleIds.Notes => Notes(material),
            ModuleIds.Title => [new ParagraphBlock { Runs = [Run.Bold(string.IsNullOrWhiteSpace(material.Details.Title) ? "Untitled recording" : material.Details.Title.Trim())] }],
            ModuleIds.CustomText => CustomText(module.CustomText),
            _ when definition is { Source: ModuleSource.Ai } => null,
            _ when definition is { Source: ModuleSource.User } => CustomText(module.CustomText),
            _ => [Note(NotDiscussed)],
        };
    }

    /// <summary>The Full transcript: every segment exactly as stored (speaker name as the transcript shows it, start time, text).</summary>
    public static TranscriptBlock FullTranscript(RecordingMaterial material)
    {
        ArgumentNullException.ThrowIfNull(material);
        var names = material.SpeakerNames;
        var segments = (material.Transcript?.Segments ?? []).OrderBy(s => s.Start).Select(s => new TranscriptLine
        {
            Id = s.Id,
            Speaker = s.Speaker is { } id && names.TryGetValue(id, out var name) ? name : "Unknown speaker",
            T = s.Start,
            Text = s.Text,
        }).ToList();
        var chapters = material.Annotations.Chapters.OrderBy(c => c.AtMs).Select(c => new TranscriptChapter { T = c.AtMs / 1000.0, Title = c.Title }).ToList();
        return new TranscriptBlock { Segments = segments, Chapters = chapters };
    }

    /// <summary>
    /// The participants: the names in the recording details, then the identified speakers that have a name (not
    /// "Speaker 2"), each once. Never inferred from what was said.
    /// </summary>
    public static IReadOnlyList<string> Participants(RecordingMaterial material)
    {
        ArgumentNullException.ThrowIfNull(material);
        var names = new List<string>();
        void Add(string? name)
        {
            var value = name?.Trim();
            if (!string.IsNullOrEmpty(value) && !names.Contains(value, StringComparer.OrdinalIgnoreCase))
            {
                names.Add(value);
            }
        }

        foreach (var participant in material.Details.Participants)
        {
            Add(participant);
        }

        foreach (var speaker in material.Transcript?.Speakers ?? [])
        {
            if (speaker.Renamed || !DefaultSpeakerName().IsMatch(speaker.Name))
            {
                Add(speaker.Name);
            }
        }

        return names;
    }

    /// <summary>The names an owner may be: participants and speaker names exactly as written.</summary>
    public static IReadOnlyList<string> KnownPeople(RecordingMaterial material) => Participants(material);

    /// <summary>The agenda items with the coverage the user marked (<c>agenda.setCovered</c>).</summary>
    public static IReadOnlyList<AgendaItem> Agenda(RecordingMaterial material)
    {
        ArgumentNullException.ThrowIfNull(material);
        return material.Details.Agenda.Items;
    }

    /// <summary>The purpose as entered in the details, or <c>null</c>.</summary>
    public static string? Purpose(RecordingMaterial material)
    {
        ArgumentNullException.ThrowIfNull(material);
        return string.IsNullOrWhiteSpace(material.Details.Purpose) ? null : material.Details.Purpose.Trim();
    }

    /// <summary>Transcript segment ids the user highlighted: the Quote module prefers them.</summary>
    public static IReadOnlyList<string> QuoteCandidates(RecordingMaterial material)
    {
        ArgumentNullException.ThrowIfNull(material);
        return material.Annotations.Highlights.Where(h => h.SegmentId is not null).OrderBy(h => h.AtMs).Select(h => h.SegmentId!).Distinct(StringComparer.Ordinal).ToList();
    }

    public static ParagraphBlock Note(string text) => new() { Runs = [Run.Note(text)] };

    private static List<Block> Chapters(RecordingMaterial material)
    {
        var chapters = material.Annotations.Chapters.OrderBy(c => c.AtMs).ToList();
        return chapters.Count == 0
            ? [Note("The recording has no chapters.")]
            : [new TimelineBlock { Entries = chapters.Select(c => new TimelineEntry { T = c.AtMs / 1000.0, Runs = [Run.Plain(c.Title)] }).ToList() }];
    }

    private static List<Block> Highlights(RecordingMaterial material)
    {
        var highlights = material.Annotations.Highlights.OrderBy(h => h.AtMs).ToList();
        if (highlights.Count == 0)
        {
            return [Note("No moments were highlighted.")];
        }

        var segments = material.Transcript?.Segments ?? [];
        var names = material.SpeakerNames;
        var blocks = new List<Block>();
        foreach (var highlight in highlights)
        {
            var segment = highlight.SegmentId is { } id ? segments.FirstOrDefault(s => s.Id == id) : null;
            var text = segment?.Text ?? highlight.Note;
            if (string.IsNullOrWhiteSpace(text))
            {
                continue;
            }

            blocks.Add(new QuoteBlock
            {
                Runs = segment is not null && !string.IsNullOrWhiteSpace(highlight.Note)
                    ? [Run.Plain(text), Run.Note(" — " + highlight.Note.Trim())]
                    : [Run.Plain(text)],
                Attribution = segment?.Speaker is { } speaker && names.TryGetValue(speaker, out var name) ? name : null,
                T = segment?.Start ?? highlight.AtMs / 1000.0,
            });
        }

        return blocks.Count == 0 ? [Note("No moments were highlighted.")] : blocks;
    }

    private static List<Block> Notes(RecordingMaterial material)
    {
        var items = new List<ListItem>();
        foreach (var line in (material.Details.Notes ?? string.Empty).Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n'))
        {
            if (!string.IsNullOrWhiteSpace(line))
            {
                items.Add(new ListItem { Runs = [Run.Plain(line.Trim().TrimStart('-', '*', '•').Trim())] });
            }
        }

        foreach (var highlight in material.Annotations.Highlights.Where(h => h.SegmentId is not null && !string.IsNullOrWhiteSpace(h.Note)).OrderBy(h => h.AtMs))
        {
            items.Add(new ListItem { Runs = [Run.Plain(highlight.Note.Trim() + " "), Run.Timestamp(highlight.AtMs / 1000.0)] });
        }

        return items.Count == 0 ? [Note("No notes were written.")] : [new ListBlock { Items = items }];
    }

    private static List<Block> CustomText(string? text)
    {
        var paragraphs = (text ?? string.Empty).Replace("\r\n", "\n", StringComparison.Ordinal).Split("\n\n", StringSplitOptions.RemoveEmptyEntries)
            .Select(p => p.Trim())
            .Where(p => p.Length > 0)
            .Select(p => (Block)new ParagraphBlock { Runs = [Run.Plain(p)] })
            .ToList();
        return paragraphs.Count == 0 ? [new ParagraphBlock { Runs = [Run.Plain(string.Empty)] }] : paragraphs;
    }

    [GeneratedRegex(@"^Speaker \d+$", RegexOptions.CultureInvariant)]
    private static partial Regex DefaultSpeakerName();
}
