// Copies the bundled font files from the @fontsource dev dependencies into public/fonts,
// writes the matching @font-face rules to src/styles/fonts.css and the OFL texts to
// public/fonts/LICENSE-OFL.txt. Fonts are bundled so the app never fetches them at runtime.
//
// Run after changing a @fontsource version: npm run fonts
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const uiRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(uiRoot, 'public', 'fonts');

// Unicode ranges as published by Fontsource for these subsets.
const subsets = {
  latin:
    'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  'latin-ext':
    'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
};

const families = [
  { family: 'Manrope', pkg: '@fontsource/manrope', file: 'manrope', weights: [400, 500, 600, 700, 800] },
  { family: 'JetBrains Mono', pkg: '@fontsource/jetbrains-mono', file: 'jetbrains-mono', weights: [400, 500] },
];

mkdirSync(outDir, { recursive: true });

const rules = [];
const licenses = [];
for (const { family, pkg, file, weights } of families) {
  const pkgDir = join(uiRoot, 'node_modules', pkg);
  const version = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8')).version;
  for (const weight of weights) {
    // latin-ext first so the browser picks the narrower latin file for the common range.
    for (const subset of ['latin-ext', 'latin']) {
      const name = `${file}-${subset}-${weight}-normal.woff2`;
      copyFileSync(join(pkgDir, 'files', name), join(outDir, name));
      rules.push(
        `@font-face {\n` +
          `  font-family: '${family}';\n` +
          `  font-style: normal;\n` +
          `  font-display: block;\n` +
          `  font-weight: ${weight};\n` +
          `  src: url('/fonts/${name}') format('woff2');\n` +
          `  unicode-range: ${subsets[subset]};\n` +
          `}`,
      );
    }
  }
  licenses.push(`${family} (from ${pkg} ${version})\n\n${readFileSync(join(pkgDir, 'LICENSE'), 'utf8').trim()}`);
}

const header =
  '/* Generated by scripts/copy-fonts.mjs from the @fontsource packages. Do not edit by hand. */\n' +
  '/* Manrope and JetBrains Mono are licensed under the SIL Open Font License 1.1 (public/fonts/LICENSE-OFL.txt). */\n\n';
writeFileSync(join(uiRoot, 'src', 'styles', 'fonts.css'), header + rules.join('\n\n') + '\n');

const separator = '\n\n' + '='.repeat(72) + '\n\n';
writeFileSync(
  join(outDir, 'LICENSE-OFL.txt'),
  'Fonts bundled with Memento. Each is licensed under the SIL Open Font License, Version 1.1.' +
    separator +
    licenses.join(separator) +
    '\n',
);

console.log(`Copied ${rules.length} font files to public/fonts and wrote src/styles/fonts.css.`);
