using System.Text.Json.Serialization;
using Memento.Core.Bridge.Contracts;

namespace Memento.Core.Bridge;

/// <summary>Source-generated serialization for every bridge contract. Unknown request fields are rejected.</summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow)]
[JsonSerializable(typeof(BridgeRequest))]
[JsonSerializable(typeof(BridgeResponse))]
[JsonSerializable(typeof(BridgeError))]
[JsonSerializable(typeof(EmptyParams))]
[JsonSerializable(typeof(EmptyResult))]
[JsonSerializable(typeof(AppVersionResult))]
[JsonSerializable(typeof(SettingsSnapshot))]
[JsonSerializable(typeof(SettingsSetParams))]
[JsonSerializable(typeof(LibraryListParams))]
[JsonSerializable(typeof(LibraryListResult))]
[JsonSerializable(typeof(LibraryProcessingResult))]
[JsonSerializable(typeof(OpenExternalParams))]
[JsonSerializable(typeof(OpenExternalResult))]
[JsonSerializable(typeof(RecordingIdParams))]
[JsonSerializable(typeof(Project))]
[JsonSerializable(typeof(ProjectUpdateDetailsParams))]
[JsonSerializable(typeof(ProjectRenameParams))]
[JsonSerializable(typeof(ProjectDeleteEstimateResult))]
[JsonSerializable(typeof(ChapterParams))]
[JsonSerializable(typeof(ChapterIdParams))]
[JsonSerializable(typeof(ChaptersResult))]
[JsonSerializable(typeof(HighlightParams))]
[JsonSerializable(typeof(HighlightIdParams))]
[JsonSerializable(typeof(HighlightsResult))]
[JsonSerializable(typeof(TopicParams))]
[JsonSerializable(typeof(TopicIdParams))]
[JsonSerializable(typeof(TopicsResult))]
[JsonSerializable(typeof(SourcesListResult))]
[JsonSerializable(typeof(RecordingStartParams))]
[JsonSerializable(typeof(RecordingStartResult))]
[JsonSerializable(typeof(RecordingSetSourceParams))]
[JsonSerializable(typeof(TracksResult))]
[JsonSerializable(typeof(SessionParams))]
[JsonSerializable(typeof(RecordingMarkHighlightParams))]
[JsonSerializable(typeof(HighlightResult))]
[JsonSerializable(typeof(RecordingStopResult))]
[JsonSerializable(typeof(RecordingCurrentResult))]
[JsonSerializable(typeof(RecoveryListResult))]
[JsonSerializable(typeof(PickFolderParams))]
[JsonSerializable(typeof(PickFolderResult))]
[JsonSerializable(typeof(FooterStatusPayload))]
[JsonSerializable(typeof(BridgeEventEnvelope<ThemeChangedPayload>))]
[JsonSerializable(typeof(BridgeEventEnvelope<FooterStatusPayload>))]
[JsonSerializable(typeof(BridgeEventEnvelope<RecordingStatePayload>))]
[JsonSerializable(typeof(BridgeEventEnvelope<RecordingLevelsPayload>))]
[JsonSerializable(typeof(BridgeEventEnvelope<SourceLostPayload>))]
[JsonSerializable(typeof(BridgeEventEnvelope<StoppedByHostPayload>))]
[JsonSerializable(typeof(BridgeEventEnvelope<LibraryChangedPayload>))]
[JsonSerializable(typeof(BridgeEventEnvelope<ProcessingProgressPayload>))]
[JsonSerializable(typeof(BridgeEventEnvelope<StorageLowSpacePayload>))]
public sealed partial class BridgeJsonContext : JsonSerializerContext
{
}
